version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - run: yarn
      - run: yarn standard
      - run: docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
      - run: ./scripts/build\&push.sh
