version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - run: yarn
      - run: yarn standard
      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - run: ./scripts/build\&push.sh
