version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - run: yarn
      - run: yarn standard
      - run: docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      - run: ./scripts/build\&push.sh
